In [19]:
import numpy as np

In [20]:
#array creation
#one dimentional array
a =np.array([10,12,52,56,53])
a

array([10, 12, 52, 56, 53])

In [21]:
type(a)

numpy.ndarray

In [22]:
a.ndim

1

In [23]:
#zero dimentional array
b= np.array(10)
b

array(10)

In [24]:
b.ndim

0

In [25]:
#two dimentional array
c = np.array([[25,30,96,69]])
c.ndim

2

In [26]:
#three dimentional array
d=np.array([[[130,125,69,67]]])
d.ndim

3

In [27]:
#change the data type of the array elements.
x = np.array([10,10.5,'himu',7])
x

array(['10', '10.5', 'himu', '7'], dtype='<U32')

In [28]:
type(x)

numpy.ndarray

In [31]:
y = np.array([10,10.5,7],dtype = 'float')
y

array([10. , 10.5,  7. ])

In [34]:
y.dtype

dtype('float64')

In [37]:
#arange function to create an array

l = np.arange(20,75)
l

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74])

In [42]:
#linspace function to create an array
s = np.linspace(7,83,25,retstep = True)
s

(array([ 7.        , 10.16666667, 13.33333333, 16.5       , 19.66666667,
        22.83333333, 26.        , 29.16666667, 32.33333333, 35.5       ,
        38.66666667, 41.83333333, 45.        , 48.16666667, 51.33333333,
        54.5       , 57.66666667, 60.83333333, 64.        , 67.16666667,
        70.33333333, 73.5       , 76.66666667, 79.83333333, 83.        ]),
 3.1666666666666665)

In [49]:
#zeros function to create an array
j= np.zeros([9,9])
j

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
#ones function to create an array
l = np.ones([10,10])
l

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
# function to create an array
k = np.random.rand(7,5)
k

array([[0.65575501, 0.48172788, 0.74969965, 0.10520197, 0.51493855],
       [0.6059331 , 0.84578254, 0.05565811, 0.86944234, 0.12982992],
       [0.09468005, 0.32994709, 0.45012566, 0.66963547, 0.20237787],
       [0.02937894, 0.69364423, 0.2103179 , 0.09763449, 0.73125481],
       [0.02784094, 0.0988217 , 0.43850575, 0.08368802, 0.88821796],
       [0.80114241, 0.78700696, 0.17130638, 0.10684442, 0.61489374],
       [0.08580701, 0.57625813, 0.46129783, 0.96249451, 0.67036684]])

In [54]:
  n = np.random.random_sample(10)
  n  

array([0.07922207, 0.35973787, 0.17952334, 0.44006075, 0.92703035,
       0.09534829, 0.12514758, 0.71940342, 0.73430536, 0.42669315])

In [55]:
#slicing and indexing of an array
w = np.array([[2,6,8],[7,4,9]])
w

array([[2, 6, 8],
       [7, 4, 9]])

In [57]:
w[1,2]

9

In [58]:
w[[1,1],[1,2]]

array([4, 9])

In [59]:
w[:,2]

array([8, 9])

In [61]:
w[0,:]

array([2, 6, 8])

In [63]:
w[0,0:2]

array([2, 6])

In [64]:
w[0:1,:]

array([[2, 6, 8]])

In [65]:
w[0:,1:]

array([[6, 8],
       [4, 9]])

In [66]:
#reshaping an array

g= np.random.rand(5,6)
g

array([[0.96794087, 0.67241619, 0.17944582, 0.43775681, 0.75988733,
        0.75512554],
       [0.90415327, 0.87123769, 0.75836223, 0.56285383, 0.45161711,
        0.71313635],
       [0.78932093, 0.08742265, 0.47692364, 0.68705877, 0.70247582,
        0.345532  ],
       [0.99888667, 0.02672931, 0.42276863, 0.93414742, 0.89570067,
        0.8788253 ],
       [0.39669457, 0.45131831, 0.39165602, 0.75480578, 0.92414897,
        0.04539901]])

In [69]:
g.reshape(-1,3)

array([[0.96794087, 0.67241619, 0.17944582],
       [0.43775681, 0.75988733, 0.75512554],
       [0.90415327, 0.87123769, 0.75836223],
       [0.56285383, 0.45161711, 0.71313635],
       [0.78932093, 0.08742265, 0.47692364],
       [0.68705877, 0.70247582, 0.345532  ],
       [0.99888667, 0.02672931, 0.42276863],
       [0.93414742, 0.89570067, 0.8788253 ],
       [0.39669457, 0.45131831, 0.39165602],
       [0.75480578, 0.92414897, 0.04539901]])

In [75]:
g.reshape(6,5)

array([[0.96794087, 0.67241619, 0.17944582, 0.43775681, 0.75988733],
       [0.75512554, 0.90415327, 0.87123769, 0.75836223, 0.56285383],
       [0.45161711, 0.71313635, 0.78932093, 0.08742265, 0.47692364],
       [0.68705877, 0.70247582, 0.345532  , 0.99888667, 0.02672931],
       [0.42276863, 0.93414742, 0.89570067, 0.8788253 , 0.39669457],
       [0.45131831, 0.39165602, 0.75480578, 0.92414897, 0.04539901]])

In [76]:
#aggregate functions
#min,max,sum,mean,median,average,product,SD,variance,percentile etc
a

array([10, 12, 52, 56, 53])

In [79]:
a.sum()

183

In [81]:
a.mean()

36.6

In [82]:
a.min()

10

In [83]:
a.max()

56

In [86]:
a.std()

20.95328136593407

In [87]:
a.var()

439.03999999999996